### ISSUE TITLE
poe.serve and poe.app tasks mismatch

### ISSUE THREAD

**Issue by SiPaRadix** [superlinear-ai/substrate#278]
In `pyproject.toml`, the parent task is defined as `tool.poe.tasks.serve` while the sequence subtask is defined as `tool.poe.tasks.app.sequence` causing an error when trying to run any task:
```
Error: Invalid task 'serve'
     | Task definition must be a string, a list, or a table including exactly one task key
     | Available task keys: {'sequence', 'switch', 'script', 'cmd', 'ref', 'shell', 'expr'}
```
Since `serve` is used as part of the app startup command,
```dockerfile
# Expose the app.
ENTRYPOINT ["/workspaces/sts-demo/.venv/bin/poe"]
CMD ["serve"]
```
I propose to change the sequence task to `tool.poe.tasks.serve.sequence`.

**Comment by sinopeus** [comment]
Can you post the full section from `pyproject.toml` which defines that task? I can't reproduce the issue on my end and don't see any `sequence` subtask under the `serve` task.

**Comment by sipalstermans** [comment]
```
[tool.poe.tasks]  # https://github.com/nat-n/poethepoet

  [tool.poe.tasks.serve]
  help = "Serve the app"

    [[tool.poe.tasks.app.sequence]]
    cmd = "echo 'Serving app (placeholder)...'"
```
Copier answers to help reproduce:
```yaml
_commit: v1.1.0
_src_path: gh:superlinear-ai/substrate
author_email: sp@superlinear.eu
author_name: Simon
project_description: A Python app to look into a bug
project_name: Poe task bug
project_type: app
project_url: https://github.com/user/app
python_version: '3.12'
typing: optional
with_conventional_commits: true
with_fastapi_api: false
with_typer_cli: false
```
I'm assuming it's related to [this line](https://github.com/superlinear-ai/substrate/blob/1787d312b5c25600abce006ff3ad05478340bea5/template/pyproject.toml.jinja#L202) in `template/pyproject.toml.jinja`.
